#ifndef CUBEMAPGEN_VERSION_H
#define CUBEMAPGEN_VERSION_H

#define CMG_VERSION_MAJOR 1
#define CMG_VERSION_MINOR 4
#define CMG_VERSION_BUILD 159

#define CMG_VERSION_STR L"1.4.0"

#endif //CUBEMAPGEN_VERSION_H
